version: '3.8'
services:
  # 1. Приложение
  app:
    build: .
    ports:
      - "5555:5555"  # Внешний порт ПК : Внутренний порт контейнера
    environment:
      - PORT=5555
      - DB_DRIVER=org.postgresql.Driver
      - JDBC_URL=jdbc:postgresql://db:5432/law_db
      - DB_USER=law_user
      - DB_PASSWORD=law_password
    depends_on:
      - db
    restart: on-failure

  # 2. База данных
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=law_db
      - POSTGRES_USER=law_user
      - POSTGRES_PASSWORD=law_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: